<!-- 
exception :- run time error

-->
<script>
    let a = 12;
    let b = 8;
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    try {
        console.log("sum1 = ", a + c);
    }
    catch(excep)
    {
      console.log(excep)
      console.log("error is occured")
    }
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
    console.log("sum = ", a + b);
</script>